In [27]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import jaccard_score
from sklearn.metrics import confusion_matrix

In [2]:
dataset=pd.read_csv('htd.csv')
dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
dataset["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [4]:
#Separating the data and Labels
X = dataset.drop(columns='target', axis=1)
Y=dataset["target"]

In [5]:
scaler=StandardScaler()
scaler.fit(X)
StandardScaler()
standardized_data = scaler.transform(X)
standardized_data

array([[ 0.9521966 ,  0.68100522,  1.97312292, ..., -2.27457861,
        -0.71442887, -2.14887271],
       [-1.91531289,  0.68100522,  1.00257707, ..., -2.27457861,
        -0.71442887, -0.51292188],
       [-1.47415758, -1.46841752,  0.03203122, ...,  0.97635214,
        -0.71442887, -0.51292188],
       ...,
       [ 1.50364073,  0.68100522, -0.93851463, ..., -0.64911323,
         1.24459328,  1.12302895],
       [ 0.29046364,  0.68100522, -0.93851463, ..., -0.64911323,
         0.26508221,  1.12302895],
       [ 0.29046364, -1.46841752,  0.03203122, ..., -0.64911323,
         0.26508221, -0.51292188]])

In [6]:
#splitting the data for Training and testing
X=standardized_data
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.3, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

(303, 13) (212, 13) (91, 13)


In [7]:
#creating the Model
model= LogisticRegression()

In [8]:
#train the model
model.fit(X_train, Y_train)
LogisticRegression()

LogisticRegression()

In [19]:
X_train_prediction=model.predict(X_train)
training_data_accuracy=metrics.accuracy_score(X_train_prediction, Y_train)
print("accuracy:", training_data_accuracy)

accuracy: 0.8349056603773585


In [21]:
X_test_prediction=model.predict(X_test)
training_data_accuracy=metrics.accuracy_score(X_test_prediction, Y_test)

In [23]:
metrics.jaccard_score(Y_train,X_train_prediction)

0.7445255474452555

In [41]:
cm = confusion_matrix(Y_test, X_test_prediction)
print(cm)

[[31 10]
 [ 2 48]]


In [37]:
Y_test.head(20)

99     1
296    0
89     1
30     1
234    0
292    0
35     1
7      1
178    0
13     1
240    0
65     1
179    0
192    0
147    1
134    1
232    0
157    1
276    0
235    0
Name: target, dtype: int64

In [35]:
X_train_prediction

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0])